<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::adminMemories' => ['privates', '.service_locator.X08NHjN', 'get_ServiceLocator_X08NHjNService.php', true],
    'App\\Controller\\AdminController::adminUsers' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\AdminController::index' => ['privates', '.service_locator.EmueYlw', 'get_ServiceLocator_EmueYlwService.php', true],
    'App\\Controller\\ContactController::index' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\MemoryController::createMemory' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\MemoryController::deleteMemory' => ['privates', '.service_locator.W_mN37p', 'get_ServiceLocator_WMN37pService.php', true],
    'App\\Controller\\MemoryController::editMemory' => ['privates', '.service_locator.DtroHoM', 'get_ServiceLocator_DtroHoMService.php', true],
    'App\\Controller\\MemoryController::fiftiesMemories' => ['privates', '.service_locator.X08NHjN', 'get_ServiceLocator_X08NHjNService.php', true],
    'App\\Controller\\MemoryController::index' => ['privates', '.service_locator.X08NHjN', 'get_ServiceLocator_X08NHjNService.php', true],
    'App\\Controller\\MemoryController::show' => ['privates', '.service_locator.gBc7QnW', 'get_ServiceLocator_GBc7QnWService.php', true],
    'App\\Controller\\MemoryController::showFiftiesMemories' => ['privates', '.service_locator.gBc7QnW', 'get_ServiceLocator_GBc7QnWService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UserController::acceptInvitation' => ['privates', '.service_locator.QhIMbAS', 'get_ServiceLocator_QhIMbASService.php', true],
    'App\\Controller\\UserController::deleteAccount' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\UserController::deleteInvitation' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController::index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController::registration' => ['privates', '.service_locator.KmqnHF8', 'get_ServiceLocator_KmqnHF8Service.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::updatePassword' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\AdminController:adminMemories' => ['privates', '.service_locator.X08NHjN', 'get_ServiceLocator_X08NHjNService.php', true],
    'App\\Controller\\AdminController:adminUsers' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\AdminController:index' => ['privates', '.service_locator.EmueYlw', 'get_ServiceLocator_EmueYlwService.php', true],
    'App\\Controller\\ContactController:index' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\MemoryController:createMemory' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\MemoryController:deleteMemory' => ['privates', '.service_locator.W_mN37p', 'get_ServiceLocator_WMN37pService.php', true],
    'App\\Controller\\MemoryController:editMemory' => ['privates', '.service_locator.DtroHoM', 'get_ServiceLocator_DtroHoMService.php', true],
    'App\\Controller\\MemoryController:fiftiesMemories' => ['privates', '.service_locator.X08NHjN', 'get_ServiceLocator_X08NHjNService.php', true],
    'App\\Controller\\MemoryController:index' => ['privates', '.service_locator.X08NHjN', 'get_ServiceLocator_X08NHjNService.php', true],
    'App\\Controller\\MemoryController:show' => ['privates', '.service_locator.gBc7QnW', 'get_ServiceLocator_GBc7QnWService.php', true],
    'App\\Controller\\MemoryController:showFiftiesMemories' => ['privates', '.service_locator.gBc7QnW', 'get_ServiceLocator_GBc7QnWService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UserController:acceptInvitation' => ['privates', '.service_locator.QhIMbAS', 'get_ServiceLocator_QhIMbASService.php', true],
    'App\\Controller\\UserController:deleteAccount' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\UserController:deleteInvitation' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController:index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController:registration' => ['privates', '.service_locator.KmqnHF8', 'get_ServiceLocator_KmqnHF8Service.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:updatePassword' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
