<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gBc7QnW' shared service.

return $this->privates['.service_locator.gBc7QnW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'memory' => ['privates', '.errored..service_locator.gBc7QnW.App\\Entity\\Memory', NULL, 'Cannot autowire service ".service_locator.gBc7QnW": it references class "App\\Entity\\Memory" but no such service exists.'],
]);
