<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DtroHoM' shared service.

return $this->privates['.service_locator.DtroHoM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'memory' => ['privates', '.errored..service_locator.DtroHoM.App\\Entity\\Memory', NULL, 'Cannot autowire service ".service_locator.DtroHoM": it references class "App\\Entity\\Memory" but no such service exists.'],
]);
