<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.W_mN37p' shared service.

return $this->privates['.service_locator.W_mN37p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'memory' => ['privates', '.errored..service_locator.W_mN37p.App\\Entity\\Memory', NULL, 'Cannot autowire service ".service_locator.W_mN37p": it references class "App\\Entity\\Memory" but no such service exists.'],
]);
