<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.X08NHjN' shared service.

return $this->privates['.service_locator.X08NHjN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'memoryRepository' => ['privates', 'App\\Repository\\MemoryRepository', 'getMemoryRepositoryService.php', true],
]);
