<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.DtroHoM.App\Entity\Memory' shared service.

include_once $this->targetDirs[3].'/vendor/gedmo/doctrine-extensions/lib/Gedmo/Blameable/Traits/BlameableEntity.php';
include_once $this->targetDirs[3].'/vendor/gedmo/doctrine-extensions/lib/Gedmo/Timestampable/Traits/TimestampableEntity.php';
include_once $this->targetDirs[3].'/src/Entity/Memory.php';

return $this->privates['.errored..service_locator.DtroHoM.App\\Entity\\Memory'] = new \App\Entity\Memory();
