<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EmueYlw' shared service.

return $this->privates['.service_locator.EmueYlw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'memoryRepository' => ['privates', 'App\\Repository\\MemoryRepository', 'getMemoryRepositoryService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
