<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTWirxtD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTWirxtD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTWirxtD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTWirxtD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTWirxtD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TWirxtD',
    'container.build_id' => '89f8f391',
    'container.build_time' => 1581508300,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTWirxtD');
