<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxMgetX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxMgetX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLxMgetX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLxMgetX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLxMgetX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LxMgetX',
    'container.build_id' => '83ab887d',
    'container.build_time' => 1584873698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxMgetX');
